
package br.com.desafioEbix.serviceImp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Mon May 06 16:50:25 BRT 2019
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "alterar", namespace = "http://serviceImp.desafioEbix.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alterar", namespace = "http://serviceImp.desafioEbix.com.br/")

public class Alterar {

    @XmlElement(name = "pessoa")
    private br.com.desafioEbix.model.Pessoa pessoa;

    public br.com.desafioEbix.model.Pessoa getPessoa() {
        return this.pessoa;
    }

    public void setPessoa(br.com.desafioEbix.model.Pessoa newPessoa)  {
        this.pessoa = newPessoa;
    }

}

