
package br.com.desafioEbix.serviceImp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Mon May 06 16:50:25 BRT 2019
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "consultarTodosResponse", namespace = "http://serviceImp.desafioEbix.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarTodosResponse", namespace = "http://serviceImp.desafioEbix.com.br/")

public class ConsultarTodosResponse {

    @XmlElement(name = "return")
    private java.util.List<br.com.desafioEbix.model.Pessoa> _return;

    public java.util.List<br.com.desafioEbix.model.Pessoa> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<br.com.desafioEbix.model.Pessoa> new_return)  {
        this._return = new_return;
    }

}

