
package br.com.desafioEbix.serviceImp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Mon May 06 16:50:25 BRT 2019
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "excluir", namespace = "http://serviceImp.desafioEbix.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "excluir", namespace = "http://serviceImp.desafioEbix.com.br/")

public class Excluir {

    @XmlElement(name = "id")
    private java.lang.Integer id;

    public java.lang.Integer getId() {
        return this.id;
    }

    public void setId(java.lang.Integer newId)  {
        this.id = newId;
    }

}

